# main.yml

# Workflow's name
name: Build Electron App For Win/Mac

# Workflow's trigger
on:
  push:
    tags:
      - "v*.*.*"

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-10.15]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v2-beta

      # step3: remove .npmrc
      - name: remove .npmrc
        if: matrix.os == 'windows-2019'
        run: |
          del .npmrc

      - name: remove .npmrc
        if: matrix.os == 'macos-10.15'
        run: |
          rm -rf .npmrc

      # step3: npm install
      - name: npm install
        run: |
          npm install

      # step4: build app for mac/win
      - name: build windows app
        if: matrix.os == 'windows-2019'
        run: |
          npm run build
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: build mac app
        if: matrix.os == 'macos-10.15'
        run: |
          npm run build
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
